### ISSUE TITLE
Add Authentication (or Custom) Header in RelayProxy mode

### ISSUE THREAD

**Issue by theboyknowsclass** [launchdarkly/dotnet-client-sdk#37]
We would like to place an extra level of security on our relay proxy instance, so that only calls from authenticated users are allowed.

Is it possible to (add the ability to) add a custom http header to all calls coming from the client sdk?

**Comment by eli-darkly** [comment]
You can already do it like so:

```csharp
        var config = Configuration.Builder("mobile-key")
            .Http(Components.HttpConfiguration().CustomHeader("name", "value"))
            .Build();
```

That'll be applied to all HTTP requests from the SDK, regardless of whether the requests are going to the Relay Proxy or to the regular LaunchDarkly endpoints. Neither LaunchDarkly nor the Relay Proxy will _do_ anything with any authentication headers you add, but I presume this is for some kind of gateway that you're putting in between?
