### ISSUE TITLE
Has the SDK been tested on a Unity project?

### ISSUE THREAD

**Issue by JackRhodes** [launchdarkly/dotnet-client-sdk#44]
I can see from the supported platforms that the SDK has been built mostly for Xamarin + desktop apps in mind. I just wanted to check if there has been attempts to use the SDK in Unity?

I can see it targets NetStandard 2.0 so in theory it should work and be compatible as long as there is no use of JIT (as this would break on IOS unity game). However I wanted to check to see if this had been explored.

**Comment by eli-darkly** [comment]
We haven't done that ourselves. I don't know of any reason why it would not work; it's an ordinary .NET assembly.

**Comment by JackRhodes** [comment]
Thank you 👍
